### ISSUE TITLE
Scene file and data request

### ISSUE THREAD

**Issue by ligoudaner377** [NVlabs/two-shot-brdf-shape#2]
Hi, great work! Thank you for your contribution to the community.
This is more like a request than an issue.
I'm working on a similar project and want to synthesize some data. In the paper, you mentioned that you use mitsuba to render the data. I would be very grateful if you could share the scene xml file that used to create depth, normal, albedo, roughness, specular maps.
Also, if possible, can you share the material maps and illumination maps you collected, it will be very helpful to my project.

Thanks!

**Comment by JiaxiongQ** [comment]
Hi, have you known how to create the dataset?

**Comment by ligoudaner377** [comment]
> Hi, have you known how to create the dataset?

Unfortunately, No. 
But for envmaps, I found an open dataset: http://indoor.hdrdb.com/ 
which can be used to render the scene.
I hope it may help you.
